title: ACBP
description: SQL-native decision rules — equation, proofs, examples, verified metrics.
theme: jekyll-theme-cayman
markdown: kramdown
baseurl: "/acbp"         # project pages base path
url: "https://dotkboy-web.github.io"
permalink: pretty
