name: Verify ACBP Theorems

on:
  push:
    branches: [ master ]
    paths:
      - "sql/**"
      - "docs/acbp_theorems.md"
      - ".github/workflows/verify-theorems.yml"
      - "scripts/**"
  pull_request:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  verify:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: acbp
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U postgres -d acbp"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install psql client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Bootstrap demo mats (CI)
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/acbp
        run: |
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f sql/000_ci_bootstrap.sql

      - name: Run theorem verifier
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/acbp
        run: |
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f sql/verify_theorems_public_auto.sql
